[mtg.genesis]
members = [
  "a15e0b6d-76ed-4443-b83f-ade9eca2681a",
  "b9126674-b07d-49b6-bf4f-48d965b2242b",
  "15141fe4-1cfd-40f8-9819-71e453054639",
  "3e72ca0c-1bab-49ad-aa0a-4d8471d375e7"
]
# now the threshold can only be members.length * 2 / 3 + 1
threshold = 3
timestamp = 1638267095017464529

[mtg.app]
client-id = ""
session-id = ""
private-key = ""
pin-token = ""
pin = ""

[machine]
# the HEX encoded BLS public poly commitments
poly = "007d68aef83f9690b04f463e13eadd9b18f4869041f1b67e7f1a30c9d1d2c42c2f741961cea2e88cfa2680eeaac040d41f41f3fedb01e38c06f4c6058fd7e425257ad901f02f8a442ccf4f1b1d0d7d3a8e8fe791102706e575d36de1c2a4a40f2a32fa1736807486256ad8dc6a8740dfb91917cf8d15848133819275be92b67328ec57826f9050f51a078ecf62665db68cf4d77625791664c9b6918fa36ea35f02ac7d77d82af98af24d7c7695fd02b96ca3a86c18888e0b8748a9bfa74fc527054458b3967c5991e7a7abfeb310891249b234541de74ae7b4c60334776f3de20db3d76ec7d42b5f02560bb311630faf7f8ac3c56983a37a5606ba1999ca7f1a24953cf10c3b12282be82d3eb0db7c149a6efa5d1d8ae0a9abdb9cdd167d968a026eb169b5dd781efd408d27e37a6e6394f52c224140ccb7b226e7f3c74c0dd7135f9062a65360505467cae13d221b0e344616636954f0c15922e7863057ac8f0e88e0783c425f438ce2d753668a4447533dec30e72ec6b51b8fc33be90d05b4"
# the threshold BLS private share
share = ""

[quorum]
store = "/mvm/quorum"
rpc = "http://127.0.0.1:8545"
chain = 83927

[messenger]
user = ""
session = ""
key = ""
buffer = 64
conversation = ""
